apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: child-apps
    repoURL: 'https://github.com/EmilyXinyi/argocd-example-apps.git'
    targetRevision: HEAD
  project: default