apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: default  
spec:
  selector:
    app: guestbook-ui     # The selector should match labels of the Pods
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80  
  type: ClusterIP       