apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    name: in-cluster
  project: default
  source:
    path: guestbook
    repoURL: 'https://github.com/EmilyXinyi/argocd-example-apps.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true