apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kustomize-guestbook
    repoURL: 'https://github.com/EmilyXinyi/argocd-example-apps.git'
    targetRevision: HEAD
  destination:
    namespace: child-kustomize-guestbook
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true